version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    container_name: silodb
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: silodb
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345678"
      TZ: "America/Sao_Paulo"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./silodb.sql:/docker-entrypoint-initdb.d/silodb.sql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-data:
    driver: local
