-- MySQL Script generated by MySQL Workbench
-- Fri May  2 19:38:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema silodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema silodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `silodb` DEFAULT CHARACTER SET utf8 ;
USE `silodb` ;

-- -----------------------------------------------------
-- Table `silodb`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`receitas` (
  `id_receita` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_receita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`ingredientes` (
  `id_ingrediente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `fator_de_proporcao` DECIMAL(4,3) NOT NULL,
  `id_receita` INT NOT NULL,
  PRIMARY KEY (`id_ingrediente`),
  INDEX `fk_ingredientes_receitas_idx` (`id_receita` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_receitas`
    FOREIGN KEY (`id_receita`)
    REFERENCES `silodb`.`receitas` (`id_receita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`acessos` (
  `id_acesso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_acesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`usuarios_acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`usuarios_acessos` (
  `id_usuario` INT NOT NULL,
  `id_acesso` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_acesso`),
  INDEX `fk_usuarios_acessos_acessos1_idx` (`id_acesso` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_acessos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `silodb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_acessos_acessos1`
    FOREIGN KEY (`id_acesso`)
    REFERENCES `silodb`.`acessos` (`id_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`placas_medidoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`placas_medidoras` (
  `id_placa_medidora` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `timestamp_ultima_interacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_placa_medidora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`fazendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`fazendas` (
  `id_fazenda` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_fazenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`fazendas_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`fazendas_usuarios` (
  `id_fazenda` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_fazenda`, `id_usuario`),
  INDEX `fk_fazendas_usuarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_fazendas_usuarios_fazendas1`
    FOREIGN KEY (`id_fazenda`)
    REFERENCES `silodb`.`fazendas` (`id_fazenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fazendas_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `silodb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`silos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`silos` (
  `id_silo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `volume_total` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `densidade_armazenada` DECIMAL(5,2) NOT NULL,
  `id_fazenda` INT NOT NULL,
  `id_placa_medidora` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_silo`),
  INDEX `fk_silos_fazendas1_idx` (`id_fazenda` ASC) VISIBLE,
  INDEX `fk_silos_placas_medidoras1_idx` (`id_placa_medidora` ASC) VISIBLE,
  CONSTRAINT `fk_silos_fazendas1`
    FOREIGN KEY (`id_fazenda`)
    REFERENCES `silodb`.`fazendas` (`id_fazenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_silos_placas_medidoras1`
    FOREIGN KEY (`id_placa_medidora`)
    REFERENCES `silodb`.`placas_medidoras` (`id_placa_medidora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`niveis_de_silo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`niveis_de_silo` (
  `id_nivel_de_silo` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(3) NOT NULL,
  `percentual_minimo` DECIMAL(3,2) NOT NULL,
  `percentual_maximo` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id_nivel_de_silo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`medicoes_silos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`medicoes_silos` (
  `id_medicao_silo` CHAR(36) NOT NULL,
  `timestamp_medicao` TIMESTAMP NOT NULL,
  `id_silo` INT NOT NULL,
  `id_nivel_de_silo` INT NOT NULL,
  INDEX `fk_medicoes_silos_silos1_idx` (`id_silo` ASC) VISIBLE,
  PRIMARY KEY (`id_medicao_silo`),
  INDEX `fk_medicoes_silos_niveis_de_silo1_idx` (`id_nivel_de_silo` ASC) VISIBLE,
  CONSTRAINT `fk_medicoes_silos_silos1`
    FOREIGN KEY (`id_silo`)
    REFERENCES `silodb`.`silos` (`id_silo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicoes_silos_niveis_de_silo1`
    FOREIGN KEY (`id_nivel_de_silo`)
    REFERENCES `silodb`.`niveis_de_silo` (`id_nivel_de_silo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silodb`.`faixas_miliampere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`faixas_miliampere` (
  `id_faixa_miliampere` INT NOT NULL,
  `ma_minimo` DECIMAL(5,2) NOT NULL,
  `ma_maximo` DECIMAL(5,2) NOT NULL,
  `id_nivel_de_silo` INT NOT NULL,
  PRIMARY KEY (`id_faixa_miliampere`),
  INDEX `fk_faixas_miliampere_niveis_de_silo1_idx` (`id_nivel_de_silo` ASC) VISIBLE,
  CONSTRAINT `fk_faixas_miliampere_niveis_de_silo1`
    FOREIGN KEY (`id_nivel_de_silo`)
    REFERENCES `silodb`.`niveis_de_silo` (`id_nivel_de_silo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `silodb` ;

-- -----------------------------------------------------
-- Placeholder table for view `silodb`.`vw_medicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silodb`.`vw_medicoes` (`id_silo` INT, `timestamp_medicao` INT, `nivel` INT, `percentual_minimo` INT, `percentual_maximo` INT, `volume_minimo` INT, `volume_maximo` INT, `peso_minimo` INT, `peso_maximo` INT);

-- -----------------------------------------------------
-- View `silodb`.`vw_medicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `silodb`.`vw_medicoes`;
USE `silodb`;
CREATE  OR REPLACE VIEW `vw_medicoes` AS
select `s`.`id_silo`,
       `ms`.`timestamp_medicao`,
       `ns`.`nivel`,
       (`ns`.`percentual_minimo` * 100) AS `percentual_minimo`,
       (`ns`.`percentual_maximo` * 100) AS `percentual_maximo`,
       (`s`.`volume_total` * `ns`.`percentual_minimo`) AS `volume_minimo`,
       (`s`.`volume_total` * `ns`.`percentual_maximo`) AS `volume_maximo`,
       (`s`.`densidade_armazenada` * `s`.`volume_total` * `ns`.`percentual_minimo`) AS `peso_minimo`,
       (`s`.`densidade_armazenada` * `s`.`volume_total` * `ns`.`percentual_maximo`) AS `peso_maximo` 
       from `silodb`.`medicoes_silos` `ms` 
       join `silodb`.`niveis_de_silo` `ns` on `ns`.`id_nivel_de_silo` = `ms`.`id_nivel_de_silo`
       join `silodb`.`silos` `s` on `ms`.`id_silo` = `s`.`id_silo`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
